### Get most important information about all products that are offered
GET http://localhost:4000/product HTTP/1.1
Accept: application/json

### Get product categories that exist.
GET http://localhost:4000/categories HTTP/1.1
Accept: application/json

### Get most important information about products for a specific categories
GET http://localhost:4000/product?brand=starbucks&roast=mediumroast&discount=true HTTP/1.1
Accept: application/json

### Get all details about a specific product
GET http://localhost:4000/product/0 HTTP/1.1
Accept: application/json

### Get the shopping basket content for a specific user.
GET http://localhost:4000/basket/1 HTTP/1.1
Accept: application/json

### Put a product in the basket for a specific user.
### POST For security if auth existed
PUT http://localhost:4000/basket HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "userId": 2,
  "productId": 3
}

### Remove one count of a product from the basket for a specific user.
DELETE http://localhost:4000/basket HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "productId": 3,
  "all": false
}

### Remove product completely from the basket for a specific user.
DELETE http://localhost:3000/basket HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "productId": 3,
  "all": true
}


### Authenticate user
POST http://localhost:3000/user/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "emassasd2si2l2@email.com",
  "password": "1234"
}

### Register user
POST http://localhost:3000/user/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "username": "Testasd4",
  "password": "1234",
  "email": "emassasd2si2l2@email.com"
}


